name: program_language_colors
description: Package used to get color by programming language, referenced from Github.
version: 1.0.0
homepage: https://sondv.dev/
repository: https://github.com/sondv301/program_language_colors

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

